import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"

import "./globals.css";

const spartan = League_Spartan({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  // weight: ["100", "200", "300", "400" , "500", "600", "700", "800","900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spartan.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
